TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.01
  max_vel_theta: 0.5 #1.0
  min_in_place_vel_theta: 0.4 #0.4

  acc_lim_theta: 2.0 #3.2 
  acc_lim_x: 1.5 # 2.5
  acc_lim_y: 1.5 #2.5

  holonomic_robot: false
  latch_xy_goal_tolerance: true
