global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
global_costmap/obstacle_layer:
  #No local, prehaps temporary, obstacles should be influence the global costmap.
  enabled: false