robot:
# Simulation settings for using moveit_sim_controllers
  moveit_sim_hw_interface:
    joint_model_group: Arm
    joint_model_group_pose: start
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      #- joint_1_1_wheel
      #- joint_1_2_wheel
      #- joint_1_3_wheel
      #- joint_1_4_wheel
      - joint_2_Arm
      - joint_3_Arm
      - joint_4_Arm
      - joint_5_Arm
    sim_control_mode: 1  # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  #joint_state_controller:
  #  type: joint_state_controller/JointStateController
  #  publish_rate: 50
  #controller_list:
  #  - name: joint_trajectory_controller
  #    action_ns: follow_joint_trajectory
  #    default: True
  #    type: FollowJointTrajectory
  #    joints:
  #      - joint_2_Arm
  #      - joint_3_Arm
  #      - joint_4_Arm
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - joint_2_Arm
        - joint_3_Arm
        - joint_4_Arm
        - joint_5_Arm
    gains:
      joint_2_Arm:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_3_Arm:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_4_Arm:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_5_Arm:
        p: 0
        d: 0
        i: 0
        i_clamp: 1
    constraints:
      goal_time: 4.0
      stopped_velocity_tolerance: 1.0
      joint_2_Arm:
        goal: 0.5
        trajectory: 1.0
      joint_3_Arm:
        goal: 0.5
        trajectory: 1.0
      joint_4_Arm:
        goal: 0.5
        trajectory: 1.0