obstacle_range: 3.0 #3.0
raytrace_range: 3.0 #3.0
footprint: [[0.195, 0.205], [0.195, -0.205], [-0.195, -0.205], [-0.195, 0.205]]
#robot_radius: ir_of_robot
inflation_radius: 0.13

observation_sources: point_cloud_sensor ##Quitar pointcloud to laser?
#laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: optical, data_type: PointCloud2, topic: depth/points, marking: true, clearing: true}

